process.env.SENTRY_DNS = "SENTRY_DNS";
process.env.NEXT_PUBLIC_ANALYTICS_WRITE_KEY_DESKTOP = "NEXT_PUBLIC_ANALYTICS_WRITE_KEY_DESKTOP";
process.env.NEXT_PUBLIC_ANALYTICS_WRITE_KEY_MOBILE = "NEXT_PUBLIC_ANALYTICS_WRITE_KEY_MOBILE";
