import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import TransportProvider from "@/components/TransportProvider";
import { StyleProvider } from "@/styles/provider";
import { ReduxProvider } from "@/redux/provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactElement }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ReduxProvider>
          <TransportProvider>
            <StyleProvider>{children}</StyleProvider>
          </TransportProvider>
        </ReduxProvider>
      </body>
    </html>
  );
}
